package com.example.simple.constants

const val ADDRESS = "Address"
const val LOGO = "Logo"
const val REGISTER = "Register"
const val PRODUCT = "Product"
const val SERVICE = "Service"
const val SUPPORT = "Support"
const val VENDAS = "Vendas"
const val MARKETING = "MarketingDigital"
const val ACORDO = "Acordo"
const val PRODUCTSICON = "productsicon"
const val SHOP = "shop"
const val SERVICES = "services"
const val OPPORTUNITY = "opportunity1"
const val PRODUCT1 = "product1"
const val PRODUCT2 = "product2"
const val PRODUCT3 = "product3"
const val PRODUCT4 = "product5"
const val PRODUCT5 = "product5"
const val PRODUCT6 = "product6"
const val BANNER = "banner"
const val BACKBUTTON = "BackButton"
const val NOTIFICATION = "Notification"
const val INFORMATION = "LegalInformation"
const val POLICY = "PolicyPrivacy"
const val EXIT = "Sair"
const val LOJA = "MinhaLoja"
const val PUBLICACOES = "Publicacoes"
const val PROFILE = "perfil"

