# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Simple' do
  use_frameworks!
  pod 'Beagle'
  pod 'Beagle/Preview'
  pod 'YogaKit', :git => 'https://github.com/ZupIT/YogaKit'

  target 'SimpleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
