package br.com.example.simple.constants

const val ADDRESS = "Address"
const val LOGO = "Logo"
const val REGISTER = "Register"
const val PRODUCT = "Product"
const val SERVICE = "Service"
const val SUPPORT = "Support"
const val VENDAS = "Vendas"
const val MARKETING = "MarketingDigital"
const val ACORDO = "Acordo"
const val MORE = "More"
const val BACKBUTTON = "BackButton"
const val NOTIFICATION = "Notification"
const val INFORMATION = "LegalInformation"
const val POLICY = "PolicyPrivacy"
const val EXIT = "Sair"
const val LOJA = "MinhaLoja"
const val PRODUTOS = "Produtos"
const val PUBLICACOES = "Publicacoes"
const val DICAS = "Dicas"
const val MAIS = "Mais"

