name: Deploy BFF to Heroku

on:
  release:
    types: [created]

jobs:
  deploy:
    name: Heroku Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
            java-version: 11
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: check
        working-directory: BFF
        run: mvn clean verify
      - name: login to heroku container registry
        env:
          HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
        run: heroku container:login
      - name: download heroku plugin deploy
        run: heroku plugins:install heroku-cli-deploy
      - name: build and push
        working-directory: BFF
        env:
          HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
        run: heroku deploy:jar target/*.jar --app simple-hacka